### ISSUE TITLE
Support for multiple annotation targets

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [annotorious/annotorious-openseadragon#147]
Hi,

I notice that the target of the annotation generated by annotorious is a single element. The web annotation specification allows multiple targets. For the web application This is a requirement for the web app I'm developing as each annotation points to a IIIF region but also to the corresponding segment of text in a TEI file. Ideally annotorious would be able to accept a collection of targets and leave untouched those that are not relevant to the image viewer. 

Is there any plan to support multiple targets in that way?

Note that in the meantime, my work around consists in an encoding/decoding layer between the single target annotorious annotations and the multi-target annotations my app loads/saves. From outside openseadragon it is multi-target, but for the purpose of the plugin it is temporarily turned into a single-target.

**Comment by rsimon** [comment]
At the moment, Annotorious will strip off extra targets, I believe, yes. So you'll need to stick with the workaround for the time being I'm afraid. I'm already working on Annotorious v3, though, which will be a complete re-write from scratch. I'll definitely put this on the list!

**Comment by geoffroy-noel-ddh** [comment]
Hi, no problem, thanks for letting me know and glad it might be part of the next version.
